
Describe "Datadog Tests" -Tag "Acceptance" {

  BeforeAll {
    # common variables
    $ResourceGroupName = "sb-test-template-rg"
    $TemplateFile = "$PSScriptRoot\..\..\ArmTemplates\Datadog\event-hub.json"
  }

  Context "When an Event Grid Topic is deployed with a name and sku" {

    BeforeAll {


      $EventhubNamespace = "$($prefix)-eh-ns"
      $EventhubName = "$($prefix)-eh"
      $TemplateParameters = @{
          eventHubName = $EventhubName
          copies = 2
      }

      # Use values if parameters passed, otherwise we rely on the default value generated by the ARM template
      $TemplateParameters["eventhubNamespace"] = $EventhubNamespace

  
      $TestTemplateParams = @{
        ResourceGroupName       = $ResourceGroupName
        TemplateFile            = $TemplateFile
        TemplateParameterObject = $TemplateParameters
      }
 
    }
    It "Should be deployed successfully" {
      $output = Test-AzureRmResourceGroupDeployment @TestTemplateParams
      $output | Should -Be $null
    }
  }
}